class ScenarioConfig:
    NAME = "base"

    BUYER_PRICE_MEMORY_WEIGHT = 0.3
    PRICE_NORMALIZER = 200

    CLAIM_RATE_MULTIPLIER = 1.0
    TRIBE_STRICTNESS_MULTIPLIER = 1.0
    PRICE_MULTIPLIER = 1.0
